title: 老哥的技术文档
description: 老哥的技术文档!
theme: just-the-docs

url: https://jasperjin01.github.io

nav_enabled: true

favicon_ico: "favicon.ico"

callouts:
  warning:
    title: 注意
    color: red
  fixme:
    title: 疑问
    color: yellow
  note:
    title: 笔记
    color: blue
  tip:
    title: 注意
    color: green

aux_links:
  "老哥的GitHub链接":
    - "https://github.com/JasperJin01"